name: mlops ci

on: 
  push:
    branches:
      - main
      - ci-cd
  pull_request: 
    branches:
      - main

jobs: 
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: train ci-cd
      run: |
        echo "train ci-cd setup successful"

  test-model:
    runs-on: ubuntu-latest
    needs: train-model  # This ensures test-model runs after train-model completes successfully

    steps:
    - name: test ci-cd
      run: |
        echo "test ci-cd setup successful"
